### ISSUE TITLE
Inconsistency between String#to_d and String#to_f

### ISSUE THREAD

**Issue by stomar** [ruby/bigdecimal#63]
String#to_d behaves differently from String#to_f for strings starting with a number that is not followed by whitespace:

``` ruby
require "bigdecimal"
require "bigdecimal/util"

"40.5degree".to_f  # => 40.5
"40.5degree".to_d  # => 0.0
```

For many other cases they behave in the same way, e.g.:

``` ruby
"40.5 degree".to_f  # => 40.5
"40.5 degree".to_d  # => 0.405e2

"foo".to_f  # => 0.0
"foo".to_d  # => 0.0

"40.5e-2".to_f  # => 0.405
"40.5e-2".to_d  # => 0.405e0
```

**Comment by feist** [comment]
Also another (potentially serious) issue.  If you pass "1.", to_f & to_i accept it, but to_d throws an exception.

2.4.1 :001 > require 'bigdecimal'
2.4.1 :002 > require 'bigdecimal/util'
2.4.1 :003 > "1.".to_i
 => 1 
2.4.1 :004 > "1.".to_f
 => 1.0 
2.4.1 :005 > "1.".to_d
ArgumentError: invalid value for BigDecimal(): "1."

**Comment by feist** [comment]
I'm seeing something even more worrying with bigdecimal-1.3.2

2.4.1 :001 > require 'bigdecimal'
 => true 
2.4.1 :002 > require 'bigdecimal/util'
 => true 
2.4.1 :006 > "1.".to_i
 => 1 
2.4.1 :007 > "1.".to_f
 => 1.0 
2.4.1 :008 > "1.".to_d
 => 0.0

**Comment by nzifnab** [comment]
I'm also seeing this issue. Looks like it's somewhat related to this fix: https://github.com/ruby/bigdecimal/pull/55

In ruby 2.3.3:

    >> "30.".to_d
    => #<BigDecimal:55adc4a76918,'0.3E2',9(18)>

In ruby 2.4.1 (and updating bigdecimal to 1.3.2):

    >> "30.".to_d
    => 0.0

**Comment by elfassy** [comment]
also
```
> "1.23other".to_d
=> 0.123e1
> "1.23degree".to_d
=> 0.0
```

**Comment by kakivis** [comment]
I guess the problem it that:
**to_d** tries to operate with **"e"**(also does the same with **"d"**) on the string to multiplies or divide by 10 times the value that succeds the letter, but when encounters another letter, it somehow sets the value to 0.0 while **to_f** ignores the word.

that's why stuff like that happens:

`> "1.23other".to_d
=> 0.123e1
> "1.23degree".to_d
=> 0.0
> "1.23kelvin".to_d
=> 0.123e1
> "1.23degree".to_f
=> 0.123e1`

I'm having some struggle with a validation, because when it tries to validates an string with my regex it refuses stuff like "41avocado" but shows to the user the value "41.00" with error, cause after the typecast, the word is just ignored, but if the letter after the number was "e" or "d" the value is set to "0.00", wich is more user-friendly to be understood...
